kakao:
  rest-api:
    key: ${KAKAO_REST_API_KEY:placeholder}

spring:
  application:
    name: airdnd
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false