spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

cors:
  allowed-origins: ${FRONTEND_URL}

toss:
  success-url: ${FRONTEND_URL}/payments/success
  fail-url: ${FRONTEND_URL}/payments/fail

logging:
  level:
    root: info

decorator:
  datasource:
    enabled: false